version: '3.8'
services:
  hypha-resources-db:
    image: postgres:14.3-alpine
    container_name: hypha-resources-db
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: rm
      POSTGRES_PASSWORD: rm
      POSTGRES_DB: myc_hypha_rm

  hypha-resources:
    image: "mycesys/hypha-resources:${IMAGE_VERSION}"
    container_name: hypha-resources
    ports:
      - "8096:8096"
    volumes:
      - ../server/keys:/app/server/keys
    environment:
      - SPRING_R2DBC_URL=${SPRING_R2DBC_URL}
      - SPRING_LIQUIBASE_URL=${SPRING_LIQUIBASE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD}
      - SSH_DEFAULT_KEY_PATH=${SSH_DEFAULT_KEY_PATH}
    depends_on:
      - hypha-resources-db
