version: '3.8'
services:
  hypha-ui:
    container_name: hypha-ui
    image: mycesys/hypha-ui:${IMAGE_VERSION}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    restart: always
