version: '3.8'
services:
  hub-ui:
    container_name: hub-ui
    image: mycesys/hub-ui:${IMAGE_VERSION}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    restart: always
