version: '3.8'
services:
  hypha-bff:
    image: "mycesys/hypha-bff:${IMAGE_VERSION}"
    container_name: hypha-bff
    ports:
      - "8100:8100"
    environment:
      - SERVICE_FILES_URL=${SERVICE_FILES_URL}
      - SERVICE_CORE_URL=${SERVICE_CORE_URL}
      - SERVICE_WORKFLOW_URL=${SERVICE_WORKFLOW_URL}
      - SERVICE_TASK_URL=${SERVICE_TASK_URL}
      - SERVICE_RESOURCE_URL=${SERVICE_RESOURCE_URL}
      - SERVICE_DASHBOARD_URL=${SERVICE_DASHBOARD_URL}
      - SERVICE_AUTH_URL=${SERVICE_AUTH_URL}
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD}
